version: '2'
services:
  jhipcats1-app:
    image: jhipcats1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipcats1-postgresql:5432/jhipcats1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipcats1-postgresql:
    extends:
      file: postgresql.yml
      service: jhipcats1-postgresql
