version: '2'
services:
  jhipcats1-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/jhipcats1/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipcats1
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
